### ISSUE TITLE
Something went wrong! Maximum retries exceeded

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [anuraghazra/github-readme-stats#2336]
### Describe the bug

![image](https://user-images.githubusercontent.com/77451351/207917225-3006dd81-ec21-4e70-9b3d-585b2b86e913.png)
Everyone on my website cannot view the stats!

### Expected behaviour

It just works

### Screenshots / Live demo link

![image](https://user-images.githubusercontent.com/77451351/207917225-3006dd81-ec21-4e70-9b3d-585b2b86e913.png)

### Additional context

My website: https://www.roessner.tech/about

**Comment by micash545** [comment]
same

**Comment by rickstaa** [comment]
@FleetAdmiralJakob and @micash545 This is a known issue when the public server is overloaded (See #1471). The error should go away when the server is not rate-limited anymore. The best solution is to deploy your own Vercel instance (see https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance).

**Comment by jaydeepkhatri** [comment]
Same issue👀👀
Thanks @rickstaa for the solution link 👍

**Comment by SAD0XER** [comment]
I am facing the same issue but mine is a little different, I have deployed the project on vercel with all perfect procedures, and the project also working fine. but after a month the token gets expires and there is an error like this 👇👇⬇️⬇️

![image](https://user-images.githubusercontent.com/79737447/210720148-95d3dd54-4dd1-4840-aa6c-e03660b7e4d8.png)

so, on the vercel, I add another token & still showed the same error, I delete the project and redeploy it again with a new token however showing that same error.

What to do now? @rickstaa @anuraghazra Please help.

**Comment by rickstaa** [comment]
> I am facing the same issue but mine is a little different, I have deployed the project on vercel with all perfect procedures, and the project also working fine. but after a month the token gets expires and there is an error like this 👇👇⬇️⬇️
> 
> ![image](https://user-images.githubusercontent.com/79737447/210720148-95d3dd54-4dd1-4840-aa6c-e03660b7e4d8.png)
> 
> so, on the vercel, I add another token & still showed the same error, I delete the project and redeploy it again with a new token however showing that same error.
> 
> What to do now? @rickstaa @anuraghazra Please help.

That's strange. The steps provided in the `🛠️ Step-by-step guide on setting up your own Vercel instance` of https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance should work. When I follow them I don't run into problems. 🤔 Do you point the on your readme to your Vercel URL instead of the public one?

**Comment by SAD0XER** [comment]
Yes.
I am pointing on my own vercel deployment.
Not a public URL.

**Comment by milovangudelj** [comment]
For me it's kind of working, but not really.

I forked the repo, deployed it to Vercel with my own domain name, added the required env variable and on GitHub it still shows the error message.

Visiting https://stats.milovangudelj.com/api?username=milovangudelj shows the stats, but on my profile's README it's bugged.

Is the request being cached and it still shows the old one from before the redeployment?
And if so, can I force a clean request in some way?

**Comment by rickstaa** [comment]
> 

@milovangudelj You are right. It could be the cache. You can purge the Vercel cache by waiting 4 hours or appending a random string to an API call (i.e. `https://stats.milovangudelj.com/api?username=milovangudelj&random=random`). However, since you recently deployed your Vercel instance, that's not the problem. You can also purge the GitHub CDN cache as explained in https://github.com/anuraghazra/github-readme-stats/issues/1471#issuecomment-1282709607.

**Comment by milovangudelj** [comment]
Yeah, that could have solved it. But I was probably too impatient cause now it's displayed properly. It was just a matter of time :clock1:

**Comment by JamesIsWack** [comment]
what the heck its broken again 😭

**Comment by rickstaa** [comment]
@JamesIsWack it's due to the popularity of the repository, I'm afraid. The graphQL API limits are being reached again. The best way to fix this is to deploy your Vercel instance (see https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance).

@anuraghazra Were you able to check whether the PATs I sent you were still valid using https://github.com/anuraghazra/github-readme-stats/pull/2178? I can send you new PATs if you want.

**Comment by rickstaa** [comment]
It should be solved for now! Feel free to comment on https://github.com/anuraghazra/github-readme-stats/issues/1772 if things strat to happen again.
