### ISSUE TITLE
The commit count is incorrect!

### ISSUE THREAD

**Issue by lmarosestolato** [anuraghazra/github-readme-stats#3579]
### Describe the bug

The commit count is incorrect! It is considering 29 commits from this year, 20 of which are from last year.

### Expected behavior

The annual count is expected to be correct for each category.

### Screenshots / Live demo link

![Prova](https://github.com/anuraghazra/github-readme-stats/assets/85000104/12f9dc54-36db-493f-89b9-b4c0ec24537c)
![Prova2](https://github.com/anuraghazra/github-readme-stats/assets/85000104/ba4aab9c-a88b-4898-bd90-660399ef4d70)

**Comment by tyleroneil72** [comment]
I am experiencing the same problem. Hopefully this is fixed soon.

**Comment by andreped** [comment]
This seems to have been fixed now. Then again, I am using @rickstaa's variant deployed on vercel. It was 0 yesterday (not just 2024 in total), but today all commits are shown:

<img width="387" alt="Screenshot 2024-01-10 at 07 23 17" src="https://github.com/anuraghazra/github-readme-stats/assets/29090665/a3a4287c-3553-49f4-9b2f-e18bd850badf">

**Comment by rickstaa** [comment]
> This seems to have been fixed now. Then again, I am using @rickstaa's variant deployed on vercel. It was 0 yesterday (not just 2024 in total), but today all commits are shown:
> 
> <img alt="Screenshot 2024-01-10 at 07 23 17" width="387" src="https://private-user-images.githubusercontent.com/29090665/295469768-a3a4287c-3553-49f4-9b2f-e18bd850badf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzM0OTIsIm5iZiI6MTcwNDg3MzE5MiwicGF0aCI6Ii8yOTA5MDY2NS8yOTU0Njk3NjgtYTNhNDI4N2MtMzU1My00OWY0LTliMmYtZTE4YmQ4NTBiYWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA3NTMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZjEyMDRhMDBhYWExNjQ4NWZhYjY1OGZiNDZiMzFkMmI2OGZlYjc4ZWZjZDY5ODFlZTlhMWZiMzY4YWFmZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.les400sC4RuOEKEfM8u-N_zWNxzwsirnnZYVzGvOXQk">

To improve the clarity and effectiveness of your message, consider the following revision:

---

Hi @andreped and @lmarosestolato,

I wanted to address a couple of issues that have come up recently.

@andreped, I think your problems are due to a bug that was present in the codebase in the past (details in [Issue #1515](https://github.com/anuraghazra/github-readme-stats/issues/1515)). I'm happy to inform you that this issue has been resolved in both my branch and the upstream.

@lmarosestolato, regarding your concerns, there might be some confusion between 'commits' and 'contributions'. This is a typical mix-up, but understanding the distinction is crucial for accurately interpreting the data. I suggest taking a look at this discussion: [Number of Commits is Incorrect](https://github.com/anuraghazra/github-readme-stats/discussions/1770#number-of-commits-is-incorrect). It offers a clear explanation and should help clarify any misunderstandings.

**Comment by andreped** [comment]
> @andreped, I think your problems are due to a bug that was present in the codebase in the past (details in [Issue #1515](https://github.com/anuraghazra/github-readme-stats/issues/1515)). I'm happy to let you know that this issue has been resolved in both my branch and the upstream.

Thank you for the clarification! :]

**Comment by Tgentil** [comment]
Hi everyone,

I've been following this discussion,  and I wanted to share the same issue that I've encountered with my own instance. I have my own fork deployed on Vercel, and it's fully updated ("This branch is not behind the upstream"). However, I'm observing a significant discrepancy in my commit count for 2024.

As of today, January 12, 2024, my commit counter shows a total of 696 commits for 2024. However, when I verify the actual count, it's only 31 commits for this year. This discrepancy is puzzling, and I'm curious if anyone else has experienced something similar with their deployments.

Attached are screenshots of my commit card and the actual number of commits in 2024 for clarity. I hope this helps in diagnosing the issue, and I look forward to any insights or suggestions from the community.

                <img height="200em" src="https://github-readme-stats-git-master-tgentil.vercel.app/api?username=Tgentil&title_color=0891b2&text_color=ffffff&icon_color=0891b2&bg_color=1c1917&hide_border=true&show=prs_merged_percentage&show_icons=true&cache=86400"/>

**Comment by rickstaa** [comment]
> Hi everyone,
> 
> I've been following this discussion, and I wanted to share the same issue that I've encountered with my own instance. I have my own fork deployed on Vercel, and it's fully updated ("This branch is not behind the upstream"). However, I'm observing a significant discrepancy in my commit count for 2024.
> 
> As of today, January 12, 2024, my commit counter shows a total of 696 commits for 2024. However, when I verify the actual count, it's only 31 commits for this year. This discrepancy is puzzling, and I'm curious if anyone else has experienced something similar with their deployments.
> 
> Attached are screenshots of my commit card and the actual number of commits in 2024 for clarity. I hope this helps in diagnosing the issue, and I look forward to any insights or suggestions from the community.
> 
> ![GitHub Readme Stats](https://camo.githubusercontent.com/853324dd7fa628e618440350388c8cda51587a8647432717842d059efb623aec/68747470733a2f2f6769746875622d726561646d652d73746174732d6769742d6d61737465722d7467656e74696c2e76657263656c2e6170702f6170693f757365726e616d653d5467656e74696c267469746c655f636f6c6f723d30383931623226746578745f636f6c6f723d6666666666662669636f6e5f636f6c6f723d3038393162322662675f636f6c6f723d31633139313726686964655f626f726465723d747275652673686f773d7072735f6d65726765645f70657263656e746167652673686f775f69636f6e733d747275652663616368653d3836343030)
> 
> ![Captura de tela 2024-01-12 114755](https://private-user-images.githubusercontent.com/88681055/296275779-e781953e-c98e-48dc-b2da-68638300c9f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzg4NDUsIm5iZiI6MTcwNTA3ODU0NSwicGF0aCI6Ii84ODY4MTA1NS8yOTYyNzU3NzktZTc4MTk1M2UtYzk4ZS00OGRjLWIyZGEtNjg2MzgzMDBjOWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE2NTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyOGU0OGU1ZDQ4ODMzYmNmODVkNWMzN2NiZjQ1MWRkYmM1NWY1N2E3ZmE5YjUwNmFmODFjY2ViYjViM2NhMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z_kMMlTsxKsHRmqxBZrlnU35qXdmdduzhc7-4qgcm88)

Hey @Tgentil. Thanks for the information. Your problem is related to https://github.com/anuraghazra/github-readme-stats/issues/1053. Please show your support for the bug to be fixed there. When https://github.com/anuraghazra/github-readme-stats/pull/2107 is finalized and merged, the issue should be resolved.

**Comment by lmarosestolato** [comment]
> @lmarosestolato, regarding your concerns, there might be some confusion between 'commits' and 'contributions'. This is a typical mix-up, but understanding the distinction is crucial for accurately interpreting the data. I suggest taking a look at this discussion: [Number of Commits is Incorrect](https://github.com/anuraghazra/github-readme-stats/discussions/1770#number-of-commits-is-incorrect). It offers a clear explanation and should help clarify any misunderstandings.

@rickstaa Regardless of the difference between contributions and commits (which I was glad to learn) there is still a problem. See these prints:
![image](https://github.com/anuraghazra/github-readme-stats/assets/85000104/ae20ae6d-c148-44b3-b8e4-8b519db3b574)
This only contribution that appears there is from this year, more specifically the discussion we are having here, but it is marked as last year's contribution. If you have any doubts, compare with the initial prints, in which there were no contributions.
![image](https://github.com/anuraghazra/github-readme-stats/assets/85000104/4dafe02c-a3f4-4d6b-8702-475625ba0b76)
Now, notice that the majority of contributions are scheduled in February of last year, with only 10 commits scheduled for January of this year, with no other type of 'contribution' beyond them. You can confirm this by going to my profile.
Despite this, 31 commits this year are being counted. So it is not possible to say that it was just a question of interpretation of the terms.

**Comment by rickstaa** [comment]
> gentil. Thanks for the information. Your problem is related to #1053. Please show your support for the bug to be fixed there. When #2107 is finalized and merged, the issue should be resolved.

Ah, thanks for the explanation 😃. If I understand you correctly then I think https://github.com/anuraghazra/github-readme-stats/issues/3579#issuecomment-1889646319 will also be the answer to your question 🤔.

**Comment by lmarosestolato** [comment]
@rickstaa I took a look at the issues you pointed out and saw that the solution is in progress. I appreciate the time you dedicated to the solution, even though you were full of things to do. I hope your master's thesis is approved!
