### ISSUE TITLE
WakaTime Stats Card - WakaTime user profile not public (It's public and tested)

### ISSUE THREAD

**Issue by thenocturnaldevgypsy** [anuraghazra/github-readme-stats#3972]
### Describe the bug

The WakaTime Stats Card from https://github.com/anuraghazra/github-readme-stats stopped working all of a sudden in my GitHub Profile's README.md.

I tried rechecking the following:

1. The URL `https://github-readme-stats.vercel.app/api/wakatime?username=thenocturnaldevgypsy&layout=compact&theme=transparent&hide_border=true&hide=other`  is vaild / working

![Screenshot (2)](https://github.com/user-attachments/assets/b3383dba-6694-4bf0-82fd-91fe4e772b7e)

2. Checked my settings at WakaTime account:

![Untitled](https://github.com/user-attachments/assets/954319df-9ab6-4f69-aba9-72bd0a8517c3)
![Screenshot (3)](https://github.com/user-attachments/assets/2470be61-ae2c-49d2-91bb-4a0b7f556251)

3. I tried doing both codes below, both have the **WakaTime user profile not public**  error.
- HTML via IMG tags `<img width="470" valign="top" align="center" src="https://github-readme-stats.vercel.app/api/wakatime?username=thenocturnaldevgypsy&layout=compact&theme=transparent&hide_border=true&hide=other" alt="TheNocturnalDevGypsy's WakaTime stats">`

- Simple Markdown `![TheNocturnalDevGypsy's WakaTime stats](https://github-readme-stats.vercel.app/api/wakatime?username=thenocturnaldevgypsy&layout=compact&theme=transparent&hide_border=true&hide=other)` 

### Expected behavior

It should display the WakaTime Stats Card correctly: https://github-readme-stats.vercel.app/api/wakatime?username=thenocturnaldevgypsy&layout=compact&theme=transparent&hide_border=true&hide=other

**Comment by Neocifra** [comment]
@thenocturnaldevgypsy I believe the bug has been fixed, now it's showing the correct expected behavior while accessing the URL you provided.

**Comment by sakshamwithweb** [comment]
no!

**Comment by RichardTMiles** [comment]
+1 I also see this issue

**Comment by BenceSzalai** [comment]
Apparently this issue is back. Even the URL in the original Issue shows:
```
WakaTime user profile not public
```

**Comment by diasdylan** [comment]
Not sure if I'm doing something wrong but yeah, its happening to me as well.  🙁
https://github-readme-stats.vercel.app/api/wakatime?username=@diasdylan&theme=vue-dark&layout=compact 
or
https://github-readme-stats.vercel.app/api/wakatime?username=diasdylan&theme=vue-dark&layout=compact
