### ISSUE TITLE
github-readme-stats not working?

### ISSUE THREAD

**Issue by Bjk8kds** [anuraghazra/github-readme-stats#4658]
### Describe the bug

I found that github-readme-stats is not working, it is not displayed.
But the language card is still displayed.

### Screenshots / Live demo link

<img width="533" height="406" alt="Image" src="https://github.com/user-attachments/assets/03072c66-1815-4714-b1a6-0125f4d880ea" />

**Comment by homelab-alpha** [comment]
Same issue see  screenshot
<details>
  <summary><code>screenshot</code> (click to expand)</summary>
  <p>

<img width="1098" height="703" alt="Image" src="https://github.com/user-attachments/assets/5e84ef0f-ac94-4e9f-9dfa-d714f7b083c4" />

  </p>
</details>

**Comment by jkowalc** [comment]
Nothing is working for me right now. Looks like the server has crashed / is being restarted.
I am getting 503 when trying to visit [the link for my GitHub account](https://github-readme-stats.vercel.app/api/top-langs/?username=jkowalc&layout=compact&theme=dark):

```
503: SERVICE_UNAVAILABLE
Code: DEPLOYMENT_PAUSED
ID: fra1::hnp2t-1764071781261-5d9c41f340ea
```

**Comment by tigran-sargsyan-w** [comment]
<img width="823" height="566" alt="Image" src="https://github.com/user-attachments/assets/074737e5-f5a6-404f-a0d9-44d21db942da" />

**Comment by tigran-sargsyan-w** [comment]
Hi @anuraghazra  check deployment  pls

**Comment by Macorai** [comment]
I think most people have the same problem, I found it yesterday morning
我认为大多数人遇到了相同的问题，我在昨天上午发现了它
<img width="617" height="430" alt="Image" src="https://github.com/user-attachments/assets/8fda8b3d-b53f-4964-8a46-54bb1941e389" />

<img width="1299" height="385" alt="Image" src="https://github.com/user-attachments/assets/ca244bec-2ae1-4025-bf65-9e2c6bd0f93e" />

**Comment by cy-Yin** [comment]
Same problem, but TopLangs still work.

**Comment by ELDment** [comment]
Please stop cosplaying as **Cloudflare**... 💀💀💀😭

**Comment by RamessesN** [comment]
Nothing work now😂 It should be a server problem. When to fix?

**Comment by goodzou** [comment]
what's going on about Readme-stats

**Comment by RamessesN** [comment]
> what's going on about Readme-stats

you can take a look of my Readme-stats and you'll know what happened 🫠

**Comment by SaranshGolash** [comment]
Same is wih me @anuraghazra Look into the deployment of the site asap.

**Comment by RickoNoNo3** [comment]
It seems like the owner (or Vercel) blocked the deployment of the webapp.

**Comment by ikostan** [comment]
Same [here](https://github.com/ikostan)

<img width="241" height="174" alt="Image" src="https://github.com/user-attachments/assets/52fb4a24-20a7-4109-b2c7-65bfb2838591" />

**Comment by ShahzaibAhmad05** [comment]
Same here too.

**Comment by YeonwooSung** [comment]
Same here too.

**Comment by qwerty541** [comment]
Hi guys. Looks like the services consumption exceeded the configured limits on the Anurag's Vercel account. Basically this issue is a duplicate of https://github.com/anuraghazra/github-readme-stats/issues/3851. Most likely the outage will persisnt till end of month.

For now I recommend you to [deploy own instance](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#deploy-on-your-own) using your own API token. This would let you to return the cards into your profile ASAP and avoid the impact of possible future outages.

I hope on your understanding since Anurag pays for the deployment from his own pockets.

**Comment by Macorai** [comment]
I deployed this instance myself, and it seems to be running smoothly. Anyway, thank you for telling us that, and thank you for everything you've done for this project
> Hi guys. Looks like the services consumption exceeded the configured limits on the Anurag's Vercel account. Basically this issue is a duplicate of https://github.com/anuraghazra/github-readme-stats/issues/3851. Most likely the outage will persisnt till end of month.
> 
> For now I recommend you to [deploy own instance](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#deploy-on-your-own) using your own API token. This would let you to return the cards into your profile ASAP and avoid the impact of possible future outages.
> 
> I hope on your understanding since Anurag pays for the deployment from his own pockets.

**Comment by Ayeez757** [comment]
喵？

**Comment by Bjk8kds** [comment]
> Hi guys. Looks like the services consumption exceeded the configured limits on the Anurag's Vercel account. Basically this issue is a duplicate of [#3851](https://github.com/anuraghazra/github-readme-stats/issues/3851). Most likely the outage will persisnt till end of month.
> 
> For now I recommend you to [deploy own instance](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#deploy-on-your-own) using your own API token. This would let you to return the cards into your profile ASAP and avoid the impact of possible future outages.
> 
> I hope on your understanding since Anurag pays for the deployment from his own pockets.

Thank you.

**Comment by Ayeez757** [comment]
> > Hi guys. Looks like the services consumption exceeded the configured limits on the Anurag's Vercel account. Basically this issue is a duplicate of [#3851](https://github.com/anuraghazra/github-readme-stats/issues/3851). Most likely the outage will persisnt till end of month.
> > For now I recommend you to [deploy own instance](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#deploy-on-your-own) using your own API token. This would let you to return the cards into your profile ASAP and avoid the impact of possible future outages.
> > I hope on your understanding since Anurag pays for the deployment from his own pockets.
> 
> Thank you.

Okay, thank you for your answer.

**Comment by qwerty541** [comment]
Let's keep this issue open while the problem persists to prevent users from creating multiple duplicates.

**Comment by LanikSJ** [comment]
> Hi guys. Looks like the services consumption exceeded the configured limits on the Anurag's Vercel account. Basically this issue is a duplicate of [#3851](https://github.com/anuraghazra/github-readme-stats/issues/3851). Most likely the outage will persisnt till end of month.
> 
> For now I recommend you to [deploy own instance](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#deploy-on-your-own) using your own API token. This would let you to return the cards into your profile ASAP and avoid the impact of possible future outages.
> 
> I hope on your understanding since Anurag pays for the deployment from his own pockets.

I don't know I guess I'm stupid or something 🙁 I tried to deploy my own instance and I can see the cards if I just hit them from my local but through GitHub Pages or anything like that they throw a broken image icon.  I have no idea what I'm doing wrong. 😑

**EDIT:** Eventually I fixed my issue using my own domain.

**Comment by Tuo-ZHANG** [comment]
also have this problem

**Comment by HangboQuan** [comment]
me too

**Comment by kennedn** [comment]
> For now I recommend you to deploy own instance using your own API token. This would let you to return the cards into your profile ASAP and avoid the impact of possible future outages.

If it helps anyone there is an alternative to deploying your own vercel instance of this repository. The [user-statistician](https://github.com/cicirello/user-statistician/tree/main/quickstart)  repository shows how to use github actions to generate stat SVGs in the profile repository that you can then reference in your ReadMe, example:

[![](https://raw.githubusercontent.com/kennedn/Kennedn/refs/heads/main/images/userstats-dark.svg)](https://github.com/cicirello/user-statistician)


 I've switched to this as I don't like the idea of having to stand up a vercel instance just to get the stats back on my ReadMe.

**Comment by mg0x7BE** [comment]
Does anyone know the answers to the questions below?

1. Where is the owner of this repo and why is he not participating in this conversation?
2. Why are you linking old posts from 2024?
3. Why isn't this fixed yet?
4. When will it be fixed?

Thanks.

BTW, the self-hosting 'solution' is ridiculous. No one in their right mind is going to create an account on shitty VERCEL just to display stars on their profile. Better to just scrap these stats entirely. What kind of joke hosting service can't manage to host simple star counts and makes people create their own instances for something this trivial?

**Comment by LanikSJ** [comment]
There are [other](https://github.com/anuraghazra/github-readme-stats/issues/4658#issuecomment-3601970216) options.

If you don't like it use something else.  This isn't a paid service you're not paying for uptime.  You're getting best effort.

You can complain all you like but I'll sum it up for you if you're too lazy to read.  The owner has done all he/she could at this point and yes it dates back to 2024.  Why? because and When? never unless you're want to put your 💰 where you mouth is.

**Comment by ArsenTech** [comment]
Same here

<img width="307" height="136" alt="Image" src="https://github.com/user-attachments/assets/d2fd5442-1b2e-463e-9ee2-80cac3893d82" />

**Comment by BuddiesD** [comment]
Why would you need Vercel? It took me about 5 minutes to create a Docker container with this repo and spin it up.
> BTW, the self-hosting 'solution' is ridiculous. No one in their right mind is going to create an account on shitty VERCEL just to display stars on their profile. Better to just scrap these stats entirely. What kind of joke hosting service can't manage to host simple star counts and makes people create their own instances for something this trivial?

**Comment by LimSR12** [comment]
After checking the CI/CD logs, it looks like the E2E tests are failing because the deployed github-readme-stats instance is returning the generic error SVG ("Something went wrong! file an issue at https://tiny.one/readme-stats") instead of the expected stats/language/repo/gist cards.
The SVG contains errors like Cannot read properties of undefined (reading 'user') and ...(reading 'viewer'), which suggests that the GitHub GraphQL response doesn’t include the expected user / viewer fields (possibly due to a missing or invalid PAT or a change in the API response). As a result, the deep equality checks between the local SVG and the deployment SVG are failing.

**Comment by Psypher1** [comment]
> > Hi guys. Looks like the services consumption exceeded the configured limits on the Anurag's Vercel account. Basically this issue is a duplicate of [#3851](https://github.com/anuraghazra/github-readme-stats/issues/3851). Most likely the outage will persisnt till end of month.
> > For now I recommend you to [deploy own instance](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#deploy-on-your-own) using your own API token. This would let you to return the cards into your profile ASAP and avoid the impact of possible future outages.
> > I hope on your understanding since Anurag pays for the deployment from his own pockets.
> 
> I don't know I guess I'm stupid or something 🙁 I tried to deploy my own instance and I can see the cards if I just hit them from my local but through GitHub Pages or anything like that they throw a broken image icon. I have no idea what I'm doing wrong. 😑
> 
> **EDIT:** Eventually I fixed my issue using my own domain.

I wanted to know where you put your token?

**Comment by LanikSJ** [comment]
> I wanted to know where you put your token?
> 

You'll need to put the token in your deployment on Vercel.

**Comment by Psypher1** [comment]
> > I wanted to know where you put your token?
> 
> You'll need to put the token in your deployment on Vercel.

I have put it, and am getting this

![Image](https://github.com/user-attachments/assets/7d8ded04-3ee6-4ecb-8580-546c9773e018)


![Image](https://github.com/user-attachments/assets/582b21b3-2b87-438a-9671-17c679113d1c)

**Comment by LanikSJ** [comment]
It needs to be an environment variable and if you're getting that error I'm guessing it's in the wrong place.

**Comment by Psypher1** [comment]
> It needs to be an environment variable and if you're getting that error I'm guessing it's in the wrong place.

I am in the Environment Variable section of Vercel though... I followed the steps in the video as well 🤔

EDIT: Nevermind, we are good

**Comment by AmodeusR** [comment]
> Why would you need Vercel? It took me about 5 minutes to create a Docker container with this repo and spin it up.

And then where do you host it? Or you're ok with showing your readme stats only when you're on on your PC and when you leave there's no problem it being broken?

**Comment by BuddiesD** [comment]
> And then where do you host it? 

I’m running it on one of my own servers inside a VM that I use only for Docker stuff.

But you could easily host it on a small VPS too, for example at Hetzner for a few bucks a month, or on the Oracle Free Tier.
On Oracle it’s free if u dont exceed the monthly free limit.

**Comment by BoBoooooo** [comment]
Same here too.

**Comment by NEVARLeVrai** [comment]
<img width="478" height="297" alt="Image" src="https://github.com/user-attachments/assets/064942b7-07c1-4829-bbec-cb1f083e70e5" />
same for me

**Comment by xxshubhamxx** [comment]
Facing the same issue

**Comment by Thesirix** [comment]
@BuddiesD 
Work for me . i use yours. you're now the new owner thx

**Comment by Cactusinhand** [comment]
Hi everyone, you can try this tool [GithubCard](https://githubcard.com/)

For more details, see #4682

**Comment by 6arash6** [comment]
Same here too.

**Comment by CompEng0001** [comment]
I ran into this problem a while ago, and somehow I found that there is another deployment of [https://github-readme-stats.vercel.app/](https://github-readme-stats.vercel.app):

- [https://github-readme-stats-eight-theta.vercel.app](https://github-readme-stats-eight-theta.vercel.app)

For example:

- [https://github-readme-stats-eight-theta.vercel.app/api?username=CompEng0001&show_icons=true&theme=material-palenight&include_all_commits=true&count_private=true](https://github-readme-stats-eight-theta.vercel.app/api?username=CompEng0001&show_icons=true&theme=material-palenight&include_all_commits=true&count_private=true)

**Comment by Bjk8kds** [comment]
material-palenight&include_all_commits=true&count_private=true

> I ran into this problem a while ago, and somehow I found that there is another deployment of [https://github-readme-stats.vercel.app/](https://github-readme-stats.vercel.app):
> 
> * https://github-readme-stats-eight-theta.vercel.app
> 
> For example:
> 
> * https://github-readme-stats-eight-theta.vercel.app/api?username=CompEng0001&show_icons=true&theme=material-palenight&include_all_commits=true&count_private=true

Its weird not all theme available with this one.

**Comment by CompEng0001** [comment]
> material-palenight&include_all_commits=true&count_private=true
> 
> > I ran into this problem a while ago, and somehow I found that there is another deployment of [https://github-readme-stats.vercel.app/](https://github-readme-stats.vercel.app):
> > 
> > * https://github-readme-stats-eight-theta.vercel.app
> > 
> > For example:
> > 
> > * https://github-readme-stats-eight-theta.vercel.app/api?username=CompEng0001&show_icons=true&theme=material-palenight&include_all_commits=true&count_private=true
> 
> Its weird not all theme available with this one.

I mean -  I didn't test every theme, but it has been stable for me since - Feb 2023

**Comment by 6arash6** [comment]
I just deployed my own instance on Vercel, and it's working smoothly :)

**Comment by 6arash6** [comment]
Maybe the problem was the environment variable (PAT_1 on vercel) or rate limit

**Comment by emerson-proenca** [comment]
What is the current solution? Change Deployments?
If needed I can borrow some space on my local server, just send me a DM

**Comment by FilippoMB** [comment]
Fixed by forking the repo and deploying it on Vercel. Follow this video for how to do it https://www.youtube.com/watch?v=n6d4KHSKqGk&t=107s

**Comment by schnatterer** [comment]
If you use GRS in a setup with build job, you can get rid of the dependency to any online-service for rendering the stats by pre-rendering them in the job.
For example with GitHub actions this is rather simple. Here is what I did: https://github.com/schnatterer/info/commit/556f0a55be2052a4fa8d44e95ef351e0819482dd
This is inspired by [utkuozdemir/github-readme-stats-selfhosted](https://github.com/utkuozdemir/github-readme-stats-selfhosted) (thanks!) but I did not want to rely on a 3rd party image here.

**Comment by SeanDictionary** [comment]
> I ran into this problem a while ago, and somehow I found that there is another deployment of [https://github-readme-stats.vercel.app/](https://github-readme-stats.vercel.app):
> 
> * https://github-readme-stats-eight-theta.vercel.app
> 
> For example:
> 
> * https://github-readme-stats-eight-theta.vercel.app/api?username=CompEng0001&show_icons=true&theme=material-palenight&include_all_commits=true&count_private=true


Great solution!

**Comment by Pranesh-2005** [comment]
Try this https://github.com/pranesh-2005/github-readme-stats-fast

**Comment by rickstaa** [comment]
As we are no longer sponsored by Vercel, we can no longer keep the public instance running. As a result, we have released a new [GitHub Action](https://github.com/marketplace/actions/github-readme-stats-action), which is now the recommended way to use the project.

This approach is significantly more stable and enables more accurate tracking. In particular, the action can traverse all repositories of a user, resulting in more precise language detection and overall statistics, including improved pull request–level metrics.

Alternatively, you can deploy the project on your [own instance](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#deploy-on-your-own).

**Comment by rickstaa** [comment]
Please see https://github.com/anuraghazra/github-readme-stats/issues/3851.

**Comment by makzylinski** [comment]
does it work for you guys?

**Comment by Pranesh-2005** [comment]
> does it work for you guys?

Try this
https://github.com/pranesh-2005/github-readme-stats-fast

**Comment by TsvetanG2** [comment]
Hi guys, better just host it yourself.

I'm leaving both actions for ReadMe Stats + Pin Project cards.
[Readme Stats](https://github.com/TsvetanG2/TsvetanG2/blob/33ba2d7fdc2389cf5ec743abcb146eeb9c1535a6/.github/workflows/readme-stats.yml)
[Pin Project cards](https://github.com/TsvetanG2/TsvetanG2/blob/33ba2d7fdc2389cf5ec743abcb146eeb9c1535a6/.github/workflows/pin-project-cards.yml)

**Comment by josiahsrc** [comment]
Not sure why it's marking it as spam, but use this repo. It fixes it: https://github.com/anuraghazra/github-readme-stats/issues/4658#issuecomment-3719741938

> https://github.com/pranesh-2005/github-readme-stats-fast

Thanks @Pranesh-2005 !

**Comment by Pranesh-2005** [comment]
> Not sure why it's marking it as spam, but use this repo. It fixes it: https://github.com/anuraghazra/github-readme-stats/issues/4658#issuecomment-3719741938
> 
> > https://github.com/pranesh-2005/github-readme-stats-fast
> 
> Thanks @Pranesh-2005 !

Thanks for Your Support ❤

**Comment by shajsat** [comment]
<img width="1511" height="845" alt="Image" src="https://github.com/user-attachments/assets/627ae616-ad18-42b5-9b3e-7b7055d3a74f" />

**Comment by Pranesh-2005** [comment]
> <img width="1511" height="845" alt="Image" src="https://github.com/user-attachments/assets/627ae616-ad18-42b5-9b3e-7b7055d3a74f" />

Try this
https://github.com/pranesh-2005/github-readme-stats-fast
It's built on top of github-readme with some caching
