### ISSUE TITLE
[BREAKING CHANGE] WakaTime Stats API Changes

### ISSUE THREAD

**Issue by anuraghazra** [anuraghazra/github-readme-stats#865]
## The Problem

~~As pointed in #863 seems like wakatime changed their public API and now we can only access the resources only if the requests is authenticated.~~

~~That's why while fetching the data it throws "FOBIDDEN" error and we cannot fetch the data.~~

## Solution

So to fix this issue I think it would be nicer if we utilize wakatime's embeddable share feature https://wakatime.com/share/embed

Benefits of this feature is that 

- No need of authentication
- Super nice JSON responses
- Users are can change how much data they need to show (last_7_days, last_30_days etc etc)
- Lot of options to customize without us needing to tinker around with the response data

## Usage 

- First users would visit https://wakatime.com/share/embed
- Select "languages"
- And generate the embed code

![image](https://user-images.githubusercontent.com/35374649/107152733-835bbf80-698f-11eb-82dd-bf23ed01d5cf.png)

After than it will give you HTML code like this: 
![image](https://user-images.githubusercontent.com/35374649/107152631-eac53f80-698e-11eb-8005-ada0f2b33126.png)

And just simply copy past the highlighted part of the string intro github readme stats url 

```
https://github-readme-stats.vercel.app/api/wakatime?shareid=yourusername/6c3e4875-6301-4b7e-955f-9251e06c7d95
```

And that's it. 

## But there's a catch 

As I noticed this json response only shows `percentage`  data and does not provides us with `time` data about the languages. 

@alanhamlett can you help us with this issue?

**Comment by anuraghazra** [comment]
Oh Ops!

Seems like wakatime api is fine and github-readme-stats is fine too! 

@LevraGav @FC5570 

Seems like in #863 the issue was that in your wakatime profile settings you did not checked these options so we cannot fetch your data 

![image](https://user-images.githubusercontent.com/35374649/107153109-d2a2ef80-6991-11eb-87c3-2700bf845010.png)


Check these checkboxes and it should work just fine.

**Comment by anuraghazra** [comment]
Well even though this was a false positive issue. 

I do like the wakatime/share feature and we might implement this feature anyways.

**Comment by LevraGav** [comment]
i have already checked those two boxes and it's still not showing up (:

**Comment by anuraghazra** [comment]
> i have already checked those two boxes and it's still not showing up (:

That's weird. 🤔 

https://wakatime.com/api/v1/users/LevraGav/stats/last_7_days

Your username responded with `{"error":"Forbidden"}`

And here is another wakatime user 
https://wakatime.com/api/v1/users/harshhhdev/stats/last_7_days
gives proper response. 

![image](https://user-images.githubusercontent.com/35374649/107153627-99b84a00-6994-11eb-8e1e-6664f51a5d9f.png)

Even github readme stats works 

![](https://github-readme-stats.vercel.app/api/wakatime?username=harshhhdev)

**Comment by LevraGav** [comment]
I have tried this method, but it still wont work for me (:
https://github-readme-stats.vercel.app/api/wakatime?shareid=LevraGav/604dd95a-d933-42e8-9c87-e3b6c7c61293
@anuraghazra

**Comment by FC5570** [comment]
I already did that tho, still didn't work, I'll try again with the embed thing

**Comment by anuraghazra** [comment]
> I have tried this method, but it still wont work for me (:
> https://github-readme-stats.vercel.app/api/wakatime?shareid=LevraGav/604dd95a-d933-42e8-9c87-e3b6c7c61293
> @anuraghazra

We did not implemented this yet, this issue is only for discussing the problem.

**Comment by SP-XD** [comment]
same issue
https://github-readme-stats.vercel.app/api/wakatime?username=sp-xd
https://wakatime.com/@spxd

**Comment by LFGaming** [comment]
hi, for me the wakatime things also don't work... I have both boxes checked. Do i have to have an account for some amount of time before it works? Because i make my wakatime account this week, but I would like to use it. [My Wakatime profile](https://wakatime.com/@LFGaming)

**Comment by SP-XD** [comment]
> > I have tried this method, but it still wont work for me (:
> > https://github-readme-stats.vercel.app/api/wakatime?shareid=LevraGav/604dd95a-d933-42e8-9c87-e3b6c7c61293
> > @anuraghazra
> 
> We did not implemented this yet, this issue is only for discussing the problem.

Why not use [activitywatch](https://github.com/ActivityWatch/activitywatch)? It is open source while waka time's free version only has 2 weeks of dashboard history.

**Comment by alanhamlett** [comment]
The public time range is customizable, and @anuraghazra has selected to show `all_time` publicly instead of the default `last_7_days`. Changing the time range works:

https://wakatime.com/api/v1/users/LevraGav/stats/all_time

**Comment by SP-XD** [comment]
> The public time range is customizable, and @anuraghazra has selected to show `all_time` publicly instead of the default `last_7_days`. Changing the time range works:
> [wakatime.com/api/v1/users/LevraGav/stats/all_time](https://wakatime.com/api/v1/users/LevraGav/stats/all_time)
> 
> To fix this, just remove the time range from the url and the user's default preference will be used:
> [wakatime.com/api/v1/users/LevraGav/stats](https://wakatime.com/api/v1/users/LevraGav/stats)

I changed my public range to all time, now it returns values instead of user not found.
https://wakatime.com/api/v1/users/spxd/stats

But still it doesn't reflect on card
https://github-readme-stats.vercel.app/api/wakatime?username=spxd

**Comment by anuraghazra** [comment]
> The public time range is customizable, and @anuraghazra has selected to show `all_time` publicly instead of the default `last_7_days`. Changing the time range works:
> https://wakatime.com/api/v1/users/LevraGav/stats/all_time
> 
> To fix this, just remove the time range from the url and the user's default preference will be used:
> https://wakatime.com/api/v1/users/LevraGav/stats

Oh i see, so just `/stats` will show the default range which users has selected for them right? 
![image](https://user-images.githubusercontent.com/35374649/107549981-78569880-6bf6-11eb-9ea5-bdb989b462e2.png)

So i think i'll push the fix right away.

**Comment by anuraghazra** [comment]
Hey @SP-XD @FC5570 @LFGaming @LevraGav the fix has been deployed and you can try it out now. (note that we have cache so if you see no changes, just add `&v=2` at the end of the url to bust the cache)

**Comment by LevraGav** [comment]
@anuraghazra thank youu, where did you deploy it?

**Comment by LevraGav** [comment]
Yeah it's working now, thank you very much guys @anuraghazra @SP-XD

**Comment by FrenzyExists** [comment]
![image](https://user-images.githubusercontent.com/47986470/109681433-d6bacb00-7b53-11eb-92d8-fb557f39c623.png)

Kinda facing a prob with wakatime...
i used this:

```md
[![Frenzy's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?username=frenzyexists)](https://github.com/anuraghazra/github-readme-stats)
```

I also tried the embeded thing:
![image](https://user-images.githubusercontent.com/47986470/109682080-78dab300-7b54-11eb-82d1-485595be219e.png)

```md
[![Frenzy's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?shareid=frenzyexists/da716838-7963-40b8-9d4c-87f4a8883ee4)](https://github.com/anuraghazra/github-readme-stats)
```

I do have the all time set n all
![image](https://user-images.githubusercontent.com/47986470/109682247-9f005300-7b54-11eb-8906-09ea7371aa26.png)

So, I have no idea what am i doing wrong

**Comment by Mongar23** [comment]
Hi, I see this is closed already but I still get the user not found error. 
This is in the read me file:
`[![Mathias' wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?shareid=Mongar23/29255064-7a9f-4c93-b8f8-5d6f08079faf)](https://github.com/anuraghazra/github-readme-stats)  `
And this is the code piece generated from WakaTime:
`$.ajax({
  type: 'GET',
  url: 'https://wakatime.com/share/@Mongar23/29255064-7a9f-4c93-b8f8-5d6f08079faf.json',
  dataType: 'jsonp',
  success: function(response) {
    console.log(response.data);
  },
});`

**Comment by WISSAL-MN** [comment]
still didn't work 🙁
